-- ====================== --
--   AREATRIGGER_TAVERN   --
-- ====================== --

ALTER TABLE `areatrigger_tavern` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
 
UPDATE `areatrigger_tavern` SET `name`='Páramos de Poniente - Posada de la Colina del Centinela' WHERE `id`='71';
UPDATE `areatrigger_tavern` SET `name`='Expedición Nesingwary' WHERE `id`='98';
UPDATE `areatrigger_tavern` SET `name`='Strahnbrad' WHERE `id`='178';
UPDATE `areatrigger_tavern` SET `name`='Horado Rajacieno' WHERE `id`='262';
UPDATE `areatrigger_tavern` SET `name`='Bosque de Elwynn - Villadorada - Posada Orgullo de León' WHERE `id`='562';
UPDATE `areatrigger_tavern` SET `name`='Montañas Crestagrana - Posada de Villa del Lago' WHERE `id`='682';
UPDATE `areatrigger_tavern` SET `name`='Bosque del Ocaso - Villa Oscura - Mesón del Cuervo Escarlata' WHERE `id`='707';
UPDATE `areatrigger_tavern` SET `name`='Laderas de Trabalomas - Posada de Costasur' WHERE `id`='708';
UPDATE `areatrigger_tavern` SET `name`='Marjal Revolcafango - Isla Theramore' WHERE `id`='709';
UPDATE `areatrigger_tavern` SET `name`='Dun Morogh - Kharanos - Destilería Cebatruenos' WHERE `id`='710';
UPDATE `areatrigger_tavern` SET `name`='Loch Modan - Thelsamar - Pensión La Cebada' WHERE `id`='712';
UPDATE `areatrigger_tavern` SET `name`='Los Humedales - Puerto de Menethil - Mesón Aguahonda' WHERE `id`='713';
UPDATE `areatrigger_tavern` SET `name`='Teldrassil - Dolanaar' WHERE `id`='715';
UPDATE `areatrigger_tavern` SET `name`='Costa Oscura - Auberdine' WHERE `id`='716';
UPDATE `areatrigger_tavern` SET `name`='Vallefresno - Astranaar' WHERE `id`='717';
UPDATE `areatrigger_tavern` SET `name`='Claros de Tirisfal - Rémol - Mesón La Horca' WHERE `id`='719';
UPDATE `areatrigger_tavern` SET `name`='Bosque de Argénteos' WHERE `id`='720';
UPDATE `areatrigger_tavern` SET `name`='Laderas de Trabalomas' WHERE `id`='721';
UPDATE `areatrigger_tavern` SET `name`='Mulgore ' WHERE `id`='722';
UPDATE `areatrigger_tavern` SET `name`='Los Baldíos' WHERE `id`='742';
UPDATE `areatrigger_tavern` SET `name`='Los Baldíos' WHERE `id`='743';
UPDATE `areatrigger_tavern` SET `name`='Durotar' WHERE `id`='843';
UPDATE `areatrigger_tavern` SET `name`='Pantano de las Penas' WHERE `id`='844';
UPDATE `areatrigger_tavern` SET `name`='Vega de Tuercespina' WHERE `id`='862';
UPDATE `areatrigger_tavern` SET `name`='Los Baldíos' WHERE `id`='982';
UPDATE `areatrigger_tavern` SET `name`='Sierra Espolón' WHERE `id`='1022';
UPDATE `areatrigger_tavern` SET `name`='Tanaris' WHERE `id`='1023';
UPDATE `areatrigger_tavern` SET `name`='Feralas' WHERE `id`='1024';
UPDATE `areatrigger_tavern` SET `name`='Feralas' WHERE `id`='1025';
UPDATE `areatrigger_tavern` SET `name`='Fortaleza de los Martillo Salvaje' WHERE `id`='1042';
UPDATE `areatrigger_tavern` SET `name`='Tierras Inhóspitas' WHERE `id`='1606';
UPDATE `areatrigger_tavern` SET `name`='Tierras Altas de Arathi' WHERE `id`='1646';
UPDATE `areatrigger_tavern` SET `name`='Desolace' WHERE `id`='2266';
UPDATE `areatrigger_tavern` SET `name`='Desolace' WHERE `id`='2267';
UPDATE `areatrigger_tavern` SET `name`='Las Mil Agujas' WHERE `id`='2286';
UPDATE `areatrigger_tavern` SET `name`='Cuna del Invierno' WHERE `id`='2287';
UPDATE `areatrigger_tavern` SET `name`='Vallefresno' WHERE `id`='2610';
UPDATE `areatrigger_tavern` SET `name`='Ciudad de Ventormenta' WHERE `id`='2746';
UPDATE `areatrigger_tavern` SET `name`='Ciudad de Ventormenta' WHERE `id`='2786';
UPDATE `areatrigger_tavern` SET `name`='Entrañas' WHERE `id`='3547';
UPDATE `areatrigger_tavern` SET `name`='Poblado Sañadiente' WHERE `id`='3690';
UPDATE `areatrigger_tavern` SET `name`='Campamento base de Grom\'gol' WHERE `id`='3886';
UPDATE `areatrigger_tavern` SET `name`='Fuerte Cenarion' WHERE `id`='3985';
UPDATE `areatrigger_tavern` SET `name`='Capilla de la Esperanza de la Luz' WHERE `id`='4085';
UPDATE `areatrigger_tavern` SET `name`='Cima del Espolón' WHERE `id`='4090';
UPDATE `areatrigger_tavern` SET `name`='Posada de Tranquillien' WHERE `id`='4108';
UPDATE `areatrigger_tavern` SET `name`='Tierras Fantasma, Tranquillien, Inicio de la posada' WHERE `id`='4109';
UPDATE `areatrigger_tavern` SET `name`='Posada de la Avanzada Azur' WHERE `id`='4240';
UPDATE `areatrigger_tavern` SET `name`='Isla Bruma de Sangre - Posada de la Avanzada de Sangre' WHERE `id`='4241';
UPDATE `areatrigger_tavern` SET `name`='Posada de la Aldea Brisa Pura' WHERE `id`='4265';
UPDATE `areatrigger_tavern` SET `name`='Marisma de Zangar, Refugio Cenarion, Afueras de la posada' WHERE `id`='4300';
UPDATE `areatrigger_tavern` SET `name`='Posada de Thrallmar' WHERE `id`='4336';
UPDATE `areatrigger_tavern` SET `name`='Posada del Bastión del Honor' WHERE `id`='4337';
UPDATE `areatrigger_tavern` SET `name`='Posada de Zabra\'jin' WHERE `id`='4373';
UPDATE `areatrigger_tavern` SET `name`='Posada de Telredor' WHERE `id`='4374';
UPDATE `areatrigger_tavern` SET `name`='Posada de Garadar' WHERE `id`='4375';
UPDATE `areatrigger_tavern` SET `name`='Posada de Telaar' WHERE `id`='4376';
UPDATE `areatrigger_tavern` SET `name`='Posada del Bastión Allerian' WHERE `id`='4377';
UPDATE `areatrigger_tavern` SET `name`='Bosque de Terokkar, Bastión Rompepedras, Posada' WHERE `id`='4378';
UPDATE `areatrigger_tavern` SET `name`='Península del Fuego Infernal, Avanzada del Halcón, Posada' WHERE `id`='4380';
UPDATE `areatrigger_tavern` SET `name`='Posada del Templo de Telhamat' WHERE `id`='4381';
UPDATE `areatrigger_tavern` SET `name`='Refugio Cenarion' WHERE `id`='4382';
UPDATE `areatrigger_tavern` SET `name`='Posada del Puerto Orebor' WHERE `id`='4383';
UPDATE `areatrigger_tavern` SET `name`='Posada de la Plaza Alalcón' WHERE `id`='4486';
UPDATE `areatrigger_tavern` SET `name`='Posada del Bastión Señor del Trueno' WHERE `id`='4494';
UPDATE `areatrigger_tavern` SET `name`='Posada de las Antiguas Laderas de Trabalomas' WHERE `id`='4498';
UPDATE `areatrigger_tavern` SET `name`='Posada de Sylvanaar' WHERE `id`='4498';
UPDATE `areatrigger_tavern` SET `name`='Antiguas Laderas de Trabalomas, detrás de la posada' WHERE `id`='4502';
UPDATE `areatrigger_tavern` SET `name`='Posada del Área 52' WHERE `id`='4521';
UPDATE `areatrigger_tavern` SET `name`='Aldea Sombraluna' WHERE `id`='4526';
UPDATE `areatrigger_tavern` SET `name`='Posada del Bastión Martillo Salvaje' WHERE `id`='4528';
UPDATE `areatrigger_tavern` SET `name`='Valle Sombraluna, Martillo Salvaje, Habitación de la posada' WHERE `id`='4529';
UPDATE `areatrigger_tavern` SET `name`='Posada de La Flecha de la Tormenta' WHERE `id`='4555';
UPDATE `areatrigger_tavern` SET `name`='Posada de la Estación de Toshley' WHERE `id`='4558';
UPDATE `areatrigger_tavern` SET `name`='Posada del Altar de Sha\'tar' WHERE `id`='4577';
UPDATE `areatrigger_tavern` SET `name`='Posada de la Aldea Mok\'Nathal' WHERE `id`='4595';
UPDATE `areatrigger_tavern` SET `name`='Posada del Sagrario de las Estrellas' WHERE `id`='4607';
UPDATE `areatrigger_tavern` SET `name`='Valle Sombraluna, Santuario de las Estrellas, Posada, en el aire' WHERE `id`='4608';
UPDATE `areatrigger_tavern` SET `name`='Posada del Soto Eterno' WHERE `id`='4640';
UPDATE `areatrigger_tavern` SET `name`='Posada del Piñón de Barro' WHERE `id`='4714';
UPDATE `areatrigger_tavern` SET `name`='Posada de la Guardia Oeste' WHERE `id`='4753';
UPDATE `areatrigger_tavern` SET `name`='Posada del Campamento Pezuña Invernal' WHERE `id`='4755';
UPDATE `areatrigger_tavern` SET `name`='Posada del Fuerte Vildervar' WHERE `id`='4756';
UPDATE `areatrigger_tavern` SET `name`='Forjaz' WHERE `id`='4769';
UPDATE `areatrigger_tavern` SET `name`='Posada del Poblado Murohelecho' WHERE `id`='4775';
UPDATE `areatrigger_tavern` SET `name`='Isla de Quel\'Danas, Posada del puerto de Tramo del Sol' WHERE `id`='4847';
UPDATE `areatrigger_tavern` SET `name`='Posada de la Avanzada Bor\'gorok' WHERE `id`='4861';
UPDATE `areatrigger_tavern` SET `name`='Posada de Pista de Aterrizaje de Palanqueta' WHERE `id`='4867';
UPDATE `areatrigger_tavern` SET `name`='Posada del Poblado Taunka\'le' WHERE `id`='4868';
UPDATE `areatrigger_tavern` SET `name`='Posada del Bastión Grito de Guerra' WHERE `id`='4910';
UPDATE `areatrigger_tavern` SET `name`='Posada de la Fortaleza Denuedo' WHERE `id`='4961';
UPDATE `areatrigger_tavern` SET `name`='Posada del Reposo Estelar' WHERE `id`='4964';
UPDATE `areatrigger_tavern` SET `name`='Posada del Refugio Pino Ámbar' WHERE `id`='4965';
UPDATE `areatrigger_tavern` SET `name`='Posada del Campamento de la Brigada de los Páramos de Poniente.' WHERE `id`='4966';
UPDATE `areatrigger_tavern` SET `name`='Posada del Campamento Oneqwah' WHERE `id`='4967';
UPDATE `areatrigger_tavern` SET `name`='Posada del Bastión de la Conquista' WHERE `id`='4970';
UPDATE `areatrigger_tavern` SET `name`='Posada del Puerto Moa\'ki' WHERE `id`='4975';
UPDATE `areatrigger_tavern` SET `name`='Posada de Kamagua' WHERE `id`='4976';
UPDATE `areatrigger_tavern` SET `name`='Posada de Unu\'pe' WHERE `id`='4977';
UPDATE `areatrigger_tavern` SET `name`='Posada de Rencor Venenoso' WHERE `id`='4979';
UPDATE `areatrigger_tavern` SET `name`='Fortaleza de Hibergarde' WHERE `id`='4993';
UPDATE `areatrigger_tavern` SET `name`='Campamento Lanzonato' WHERE `id`='5030';
UPDATE `areatrigger_tavern` SET `name`='El Martillo de Agmar' WHERE `id`='5045';
UPDATE `areatrigger_tavern` SET `name`='Tierras Ocaso Marchito' WHERE `id`='5062';
UPDATE `areatrigger_tavern` SET `name`='Zim\'Torga' WHERE `id`='5164';
UPDATE `areatrigger_tavern` SET `name`='Posada de Fuerte Escarcha' WHERE `id`='5182';
UPDATE `areatrigger_tavern` SET `name`='Posada del K3' WHERE `id`='5183';
UPDATE `areatrigger_tavern` SET `name`='Poblado Brunnhildar' WHERE `id`='5200';
UPDATE `areatrigger_tavern` SET `name`='Refugio de Pedruscón' WHERE `id`='5204';
UPDATE `areatrigger_tavern` SET `name`='Posada del campamento base de Nesingwary' WHERE `id`='5217';
UPDATE `areatrigger_tavern` SET `name`='Vanguardia Argenta' WHERE `id`='5227';
UPDATE `areatrigger_tavern` SET `name`='Cementerio de Dragones - Posada del Reposo del Dragón' WHERE `id`='5314';
UPDATE `areatrigger_tavern` SET `name`='Campamento Tunka\'lo' WHERE `id`='5323';
UPDATE `areatrigger_tavern` SET `name`='Alto de Krasus' WHERE `id`='5327';
