-- ========================= --
--    areatrigger_teleport   --
-- ========================= --

ALTER TABLE `areatrigger_teleport` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

UPDATE `areatrigger_teleport` SET `name`='Minas de la Muerte Entrada' WHERE `id`='78';
UPDATE `areatrigger_teleport` SET `name`='Empalizadas de Ventormenta Entrada' WHERE `id`='101';
UPDATE `areatrigger_teleport` SET `name`='Sótano de Ventormenta Entrada' WHERE `id`='107';
UPDATE `areatrigger_teleport` SET `name`='Sótano de Ventormenta Instancia ' WHERE `id`='109';
UPDATE `areatrigger_teleport` SET `name`='Minas de la Muerte Instancia inicial' WHERE `id`='119';
UPDATE `areatrigger_teleport` SET `name`='Minas de la muerte Instancia final' WHERE `id`='121';
UPDATE `areatrigger_teleport` SET `name`='Castillo de colmillo oscuro Fortaleza' WHERE `id`='145';
UPDATE `areatrigger_teleport` SET `name`='Castillo de colmillo oscuro Fortaleza - Entrada' WHERE `id`='194';
UPDATE `areatrigger_teleport` SET `name`='Los Baldios - Cuevas de los lamentos' WHERE `id`='226';
UPDATE `areatrigger_teleport` SET `name`='Los Baldios - Cuevas de los lamentos' WHERE `id`='228';
UPDATE `areatrigger_teleport` SET `name`='Zahúrda Rajacieno Instancia inicial' WHERE `id`='242';
UPDATE `areatrigger_teleport` SET `name`='Zahúrda Rajacieno Entrada' WHERE `id`='244';
UPDATE `areatrigger_teleport` SET `name`='Cavernas de Brazanegra Entrada' WHERE `id`='257';
UPDATE `areatrigger_teleport` SET `name`='Cavernas de Brazanegra Instancia inicial' WHERE `id`='259';
UPDATE `areatrigger_teleport` SET `name`='Uldaman Entrada' WHERE `id`='286';
UPDATE `areatrigger_teleport` SET `name`='Uldaman Instancia inicial' WHERE `id`='288';
UPDATE `areatrigger_teleport` SET `name`='Gnomeregan Instancia inicial' WHERE `id`='322';
UPDATE `areatrigger_teleport` SET `name`='Gnomeregan Entrada' WHERE `id`='324';
UPDATE `areatrigger_teleport` SET `name`='Zahúrda Rajacieno Entrada' WHERE `id`='442';
UPDATE `areatrigger_teleport` SET `name`='Zahúrda Rajacieno Instancia inicial' WHERE `id`='444';
UPDATE `areatrigger_teleport` SET `name`='Templo de Atal\'Hakkar Entrada' WHERE `id`='446';
UPDATE `areatrigger_teleport` SET `name`='Templo de Atal\'Hakkar Instancia inicial' WHERE `id`='448';
UPDATE `areatrigger_teleport` SET `name`='Mazmorras Instancia' WHERE `id`='503';
UPDATE `areatrigger_teleport` SET `name`='Gnomeregan Estación de tren entrada' WHERE `id`='523';
UPDATE `areatrigger_teleport` SET `name`='Gnomeregan Estación de tren instacia' WHERE `id`='525';
UPDATE `areatrigger_teleport` SET `name`='Teldrassil - Aldea Rut\'Theran' WHERE `id`='527';
UPDATE `areatrigger_teleport` SET `name`='Teldrassil - Darnassus' WHERE `id`='542';
UPDATE `areatrigger_teleport` SET `name`='Ventormenta - Santuario de Magos habitaciones' WHERE `id`='702';
UPDATE `areatrigger_teleport` SET `name`='Ventormenta - Santuario de Magos Portal de la torre' WHERE `id`='704';
UPDATE `areatrigger_teleport` SET `name`='Uldaman Instancia Final' WHERE `id`='882';
UPDATE `areatrigger_teleport` SET `name`='Uldaman Salida' WHERE `id`='902';
UPDATE `areatrigger_teleport` SET `name`='Zul\'Farrak Instancia Inicial' WHERE `id`='922';
UPDATE `areatrigger_teleport` SET `name`='Zul\'Farrak Entrada' WHERE `id`='924';
UPDATE `areatrigger_teleport` SET `name`='Guarida de Onyxia - Revolcafango Instancia' WHERE `id`='1064';
UPDATE `areatrigger_teleport` SET `name`='Montaña Roca Negra - Garganta de Fuego Instancia?' WHERE `id`='1466';
UPDATE `areatrigger_teleport` SET `name`='Cumbre de Roca Negra - Garganta de Fuego Instancia (Interior)' WHERE `id`='1468';
UPDATE `areatrigger_teleport` SET `name`='Cumbre de Roca Negra - Garganta de Fuego Instancia' WHERE `id`='1470';
UPDATE `areatrigger_teleport` SET `name`='Prufundidades de Roca Negra - Garganta de Fuego Instancia' WHERE `id`='1472';
UPDATE `areatrigger_teleport` SET `name`='Batalla del Monte Hyjal (Salida)' WHERE `id`='4487';
UPDATE `areatrigger_teleport` SET `name`='Batalla del Monte Hyjal, Base Alianza (Entrada)' WHERE `id`='4311';
UPDATE `areatrigger_teleport` SET `name`='Batalla del Monte Hyjal, Base Horda (Entrada)' WHERE `id`='4312';
UPDATE `areatrigger_teleport` SET `name`='Batalla del Monte Hyjal, Elfos nocturnos Base (Entrada)' WHERE `id`='4313';
UPDATE `areatrigger_teleport` SET `name`='Cavernas del Tiempo, Batalla del Monte Hyjal (Entrada) ' WHERE `id`='4319';
UPDATE `areatrigger_teleport` SET `name`='Cavernas del Tiempo, Batalla del Monte Hyjal (Salida)' WHERE `id`='4323';
UPDATE `areatrigger_teleport` SET `name`='Tren Subterráneo - Forjaz Instancia (Interior)' WHERE `id`='2166';
UPDATE `areatrigger_teleport` SET `name`='Tren Subterráneo - Ventormenta Instancia (Interior)' WHERE `id`='2171';
UPDATE `areatrigger_teleport` SET `name`='Tren Subterráneo - Ventormenta Instancia' WHERE `id`='2173';
UPDATE `areatrigger_teleport` SET `name`='Tren Subterráneo - Forjaz Instancia' WHERE `id`='2175';
UPDATE `areatrigger_teleport` SET `name`='Stratholme - Tierras de la Peste del Este Instancia' WHERE `id`='2214';
UPDATE `areatrigger_teleport` SET `name`='Stratholme - Tierras de la Peste del Este Instancia' WHERE `id`='2216';
UPDATE `areatrigger_teleport` SET `name`='Stratholme - Tierras de la Peste del Este Instancia' WHERE `id`='2217';
UPDATE `areatrigger_teleport` SET `name`='Stratholme - Tierras de la Peste del Este Instancia (Interior)' WHERE `id`='2221';
UPDATE `areatrigger_teleport` SET `name`='Sima Ígnea - Ogrimmar Instancia (Interior)' WHERE `id`='2226';
UPDATE `areatrigger_teleport` SET `name`='Sima Ígnea - Ogrimmar Instancia' WHERE `id`='2230';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (hacia la Guarida de Vermis de escarcha)' WHERE `id`='4156';
UPDATE `areatrigger_teleport` SET `name`='Sala de las Leyendas - Ogrimmar (Interior)' WHERE `id`='2530';
UPDATE `areatrigger_teleport` SET `name`='Scholomance Entrada' WHERE `id`='2567';
UPDATE `areatrigger_teleport` SET `name`='Scholomance Instancia' WHERE `id`='2568';
UPDATE `areatrigger_teleport` SET `name`='Monasterio Escarlata - Catedral (Salida)' WHERE `id`='604';
UPDATE `areatrigger_teleport` SET `name`='Monasterio Escarlata - Catedral (Entrada)' WHERE `id`='610';
UPDATE `areatrigger_teleport` SET `name`='Monasterio Escarlata - Armería (Salida)' WHERE `id`='606';
UPDATE `areatrigger_teleport` SET `name`='Monasterio Escarlata - Armería (Entrada)' WHERE `id`='612';
UPDATE `areatrigger_teleport` SET `name`='Monasterio Escarlata - Cementerio (Salida)' WHERE `id`='602';
UPDATE `areatrigger_teleport` SET `name`='Monasterio Escarlata - Cementerio (Entrada)' WHERE `id`='45';
UPDATE `areatrigger_teleport` SET `name`='Monasterio Escarlata - Librería (Salida)' WHERE `id`='608';
UPDATE `areatrigger_teleport` SET `name`='Monasterio Escarlata - Librería (Entrada)' WHERE `id`='614';
UPDATE `areatrigger_teleport` SET `name`='Guarida de Onyxia Entrada' WHERE `id`='2848';
UPDATE `areatrigger_teleport` SET `name`='Maraudon' WHERE `id`='3126';
UPDATE `areatrigger_teleport` SET `name`='Maraudon' WHERE `id`='3131';
UPDATE `areatrigger_teleport` SET `name`='Maraudon' WHERE `id`='3133';
UPDATE `areatrigger_teleport` SET `name`='Maraudon' WHERE `id`='3134';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3183';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3184';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3185';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3186';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3187';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3189';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3190';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3191';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3193';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3194';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3195';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3196';
UPDATE `areatrigger_teleport` SET `name`='La Masacre' WHERE `id`='3197';
UPDATE `areatrigger_teleport` SET `name`='Guarida Alanegra - Montaña Roca Negra - Reinos del Este' WHERE `id`='3726';
UPDATE `areatrigger_teleport` SET `name`='Cumbre de Roca Negra, desconocido' WHERE `id`='3728';
UPDATE `areatrigger_teleport` SET `name`='Zul\'Gurub Salida ' WHERE `id`='3930';
UPDATE `areatrigger_teleport` SET `name`='Zul\'Gurub Entrada ' WHERE `id`='3928';
UPDATE `areatrigger_teleport` SET `name`='Runinas de Ahn\'Qiraj (Interior)' WHERE `id`='4006';
UPDATE `areatrigger_teleport` SET `name`='Runinas de Ahn\'Qiraj (Exterior)' WHERE `id`='4008';
UPDATE `areatrigger_teleport` SET `name`='Templo Ahn\'Qiraj (Exterior)' WHERE `id`='4010';
UPDATE `areatrigger_teleport` SET `name`='Templo Ahn\'Qiraj (Interior)' WHERE `id`='4012';
UPDATE `areatrigger_teleport` SET `name`='Terrallende hacia el Portal Oscuro' WHERE `id`='4352';
UPDATE `areatrigger_teleport` SET `name`='Portal Oscuro hacia Terrallende' WHERE `id`='4354';
UPDATE `areatrigger_teleport` SET `name`='La Isla del Caminante del Sol hacia Tierras de la Peste del Este' WHERE `id`='4386';
UPDATE `areatrigger_teleport` SET `name`='Tierras de la Peste del Este hacia La Isla del Caminante del Sol ' WHERE `id`='4409';
UPDATE `areatrigger_teleport` SET `name`='Guarida de Gruul (Salida)' WHERE `id`='4534';
UPDATE `areatrigger_teleport` SET `name`='Guarida de Gruul (Entrada)' WHERE `id`='4535';
UPDATE `areatrigger_teleport` SET `name`='El Ojo de la Eternidad (Salida)' WHERE `id`='4457';
UPDATE `areatrigger_teleport` SET `name`='El Ojo (Entrada)' WHERE `id`='4470';
UPDATE `areatrigger_teleport` SET `name`='El Mechanar (Entrada)' WHERE `id`='4469';
UPDATE `areatrigger_teleport` SET `name`='El Mechanar (Salida)' WHERE `id`='4455';
UPDATE `areatrigger_teleport` SET `name`='El Arcatraz (Entrada)' WHERE `id`='4468';
UPDATE `areatrigger_teleport` SET `name`='El Arcatraz (Salida)' WHERE `id`='4461';
UPDATE `areatrigger_teleport` SET `name`='El invernáculo (Entrada)' WHERE `id`='4467';
UPDATE `areatrigger_teleport` SET `name`='El invernáculo (Salida)' WHERE `id`='4459';
UPDATE `areatrigger_teleport` SET `name`='Las Salas Arrasadas (Entrada)' WHERE `id`='4151';
UPDATE `areatrigger_teleport` SET `name`='Las Salas Arrasadas  (Salida)' WHERE `id`='4145';
UPDATE `areatrigger_teleport` SET `name`='Murallas del Fuego Infernal  (Entrada)' WHERE `id`='4150';
UPDATE `areatrigger_teleport` SET `name`='Murallas del Fuego Infernal (Salida)' WHERE `id`='4297';
UPDATE `areatrigger_teleport` SET `name`='El Recinto de los Esclavos (Salida)' WHERE `id`='4379';
UPDATE `areatrigger_teleport` SET `name`='Guarida de Magtheridon (Salida)' WHERE `id`='4149';
UPDATE `areatrigger_teleport` SET `name`='La Sotiénaga (Salida)' WHERE `id`='4367';
UPDATE `areatrigger_teleport` SET `name`='La Cámara de Vapor (Entrada)' WHERE `id`='4364';
UPDATE `areatrigger_teleport` SET `name`='Guarida de Magtheridon (Entrada)' WHERE `id`='4153';
UPDATE `areatrigger_teleport` SET `name`='El Horno de Sangre (Entrada)' WHERE `id`='4152';
UPDATE `areatrigger_teleport` SET `name`='El Horno de Sangre (Salida)' WHERE `id`='4147';
UPDATE `areatrigger_teleport` SET `name`='La Cámara de Vapor (Salida)' WHERE `id`='4366';
UPDATE `areatrigger_teleport` SET `name`='El Recinto de los Esclavos (Entrada)' WHERE `id`='4365';
UPDATE `areatrigger_teleport` SET `name`='La Sotiénaga (Entrada)' WHERE `id`='4363';
UPDATE `areatrigger_teleport` SET `name`='Laberinto de las Sombras (Salida)' WHERE `id`='4397';
UPDATE `areatrigger_teleport` SET `name`='Laberinto de las Sombras (Entrada)' WHERE `id`='4407';
UPDATE `areatrigger_teleport` SET `name`='Salas Sethekk (Entrada)' WHERE `id`='4406';
UPDATE `areatrigger_teleport` SET `name`='Salas Sethekk (Salida)' WHERE `id`='4403';
UPDATE `areatrigger_teleport` SET `name`='Tumbas de Maná (Entrada)' WHERE `id`='4405';
UPDATE `areatrigger_teleport` SET `name`='Tumbas de Maná (Salida)' WHERE `id`='4401';
UPDATE `areatrigger_teleport` SET `name`='Criptas Auchenai (Entrada)' WHERE `id`='4404';
UPDATE `areatrigger_teleport` SET `name`='Criptas Auchenai (Salida)' WHERE `id`='4399';
UPDATE `areatrigger_teleport` SET `name`='Karazhan, Entrada principal' WHERE `id`='4131';
UPDATE `areatrigger_teleport` SET `name`='Karazhan, salida principal' WHERE `id`='4436';
UPDATE `areatrigger_teleport` SET `name`='Cavernas del Tiempo, Ciénaga negra (Entrada)' WHERE `id`='4320';
UPDATE `areatrigger_teleport` SET `name`='Cavernas del Tiempo, Antiguas Laderas de Trabalomas (Entrada)' WHERE `id`='4321';
UPDATE `areatrigger_teleport` SET `name`='Cavernas del Tiempo, Antiguas Laderas de Trabalomas (Salida)' WHERE `id`='4324';
UPDATE `areatrigger_teleport` SET `name`='El Puente de Magma' WHERE `id`='2886';
UPDATE `areatrigger_teleport` SET `name`='Núcleo de Magma Entrada, Interior' WHERE `id`='2890';
UPDATE `areatrigger_teleport` SET `name`='Caverna Santuario Serpiente (Entrada)' WHERE `id`='4416';
UPDATE `areatrigger_teleport` SET `name`='Caverna Santuario Serpiente (Salida)' WHERE `id`='4418';
UPDATE `areatrigger_teleport` SET `name`='Templo Oscuro (Salida)' WHERE `id`='4619';
UPDATE `areatrigger_teleport` SET `name`='Templo Oscuro (Entrada)' WHERE `id`='4598';
UPDATE `areatrigger_teleport` SET `name`='Karazhan, Servicio (Entrada)' WHERE `id`='4135';
UPDATE `areatrigger_teleport` SET `name`='Cavernas del Tiempo, Ciénaga negra (Salida)' WHERE `id`='4322';
UPDATE `areatrigger_teleport` SET `name`='Ventormenta (Interior) - Sala de los Campeones' WHERE `id`='2534';
UPDATE `areatrigger_teleport` SET `name`='Zul\'Aman (Entrada)' WHERE `id`='4738';
UPDATE `areatrigger_teleport` SET `name`='Zul\'Aman (Salida)' WHERE `id`='4739';
UPDATE `areatrigger_teleport` SET `name`='Salto de Fe - final de caida' WHERE `id`='943';
UPDATE `areatrigger_teleport` SET `name`='Bancal del Magister (Salida)' WHERE `id`='4885';
UPDATE `areatrigger_teleport` SET `name`='Bancal del Magister (Entrada)' WHERE `id`='4887';
UPDATE `areatrigger_teleport` SET `name`='Meseta de La Fuente del Sol (Entrada)' WHERE `id`='4889';
UPDATE `areatrigger_teleport` SET `name`='Meseta de La Fuente del Sol (Salida)' WHERE `id`='4891';
UPDATE `areatrigger_teleport` SET `name`='Punto de invasión, Cataclysm (Punto de vuelta)' WHERE `id`='4562';
UPDATE `areatrigger_teleport` SET `name`='La Cuenca de Arathi - Alianza (exterior)' WHERE `id`='3948';
UPDATE `areatrigger_teleport` SET `name`='La Cuenca de Arathi - Horda (exterior)' WHERE `id`='3949';
UPDATE `areatrigger_teleport` SET `name`='La Cuenca de Arathi - Alianza (interior)' WHERE `id`='3953';
UPDATE `areatrigger_teleport` SET `name`='La Cuenca de Arathi - Horda (interior)' WHERE `id`='3954';
UPDATE `areatrigger_teleport` SET `name`='Trono de Socrethar a el continente' WHERE `id`='4523';
UPDATE `areatrigger_teleport` SET `name`='Punto de invasión, Cataclysm (Punto de vuelta)' WHERE `id`='4561';
UPDATE `areatrigger_teleport` SET `name`='Baldíos - Campo Base Mor\'shan (Garganta Grito de Guerra - Entrada Horda) ' WHERE `id`='3654';
UPDATE `areatrigger_teleport` SET `name`='Vallefresno - Bastión Ala de Plata (Garganta Grito de Guerra - Entrada Alianza) ' WHERE `id`='3650';
UPDATE `areatrigger_teleport` SET `name`='El Mechanar - El Invernáculo' WHERE `id`='4614';
UPDATE `areatrigger_teleport` SET `name`='El Invernáculo - El Mechanar' WHERE `id`='4612';
UPDATE `areatrigger_teleport` SET `name`='Valle de Alterac - Horda Salida' WHERE `id`='2606';
UPDATE `areatrigger_teleport` SET `name`='Valle de Alterac - Alianza Salida' WHERE `id`='2608';
UPDATE `areatrigger_teleport` SET `name`='Scholomance - Fuera' WHERE `id`='2549';
UPDATE `areatrigger_teleport` SET `name`='Scholomance - Fuera' WHERE `id`='2548';
UPDATE `areatrigger_teleport` SET `name`='Scholomance - Fuera' WHERE `id`='2547';
UPDATE `areatrigger_teleport` SET `name`='Tierras Fantasma, Aguja Ocaso, balconada' WHERE `id`='4233';
UPDATE `areatrigger_teleport` SET `name`='Bosque Canción Eterna, Aguja Ocaso, Pérgola alta' WHERE `id`='4267';
UPDATE `areatrigger_teleport` SET `name`='The Núcleo de Magma Ventana(Lava) Entrada' WHERE `id`='3529';
UPDATE `areatrigger_teleport` SET `name`='The Núcleo de Magma Ventana Entrada' WHERE `id`='3528';
UPDATE `areatrigger_teleport` SET `name`='DK Planta 2 hacia Planta 3 Este' WHERE `id`='5029';
UPDATE `areatrigger_teleport` SET `name`='DK Planta 3 hacia Planta 2 Oeste ' WHERE `id`='5017';
UPDATE `areatrigger_teleport` SET `name`='El Oculus (Salida)' WHERE `id`='5001';
UPDATE `areatrigger_teleport` SET `name`='El Nexo (Salida)' WHERE `id`='4981';
UPDATE `areatrigger_teleport` SET `name`='El Nexo (Entrada)' WHERE `id`='4983';
UPDATE `areatrigger_teleport` SET `name`='Pináculo de Utgarde (Salida)' WHERE `id`='4741';
UPDATE `areatrigger_teleport` SET `name`='Pináculo de Utgarde (Entrada)' WHERE `id`='4747';
UPDATE `areatrigger_teleport` SET `name`='El Bastión Violeta (Entrada)' WHERE `id`='5209';
UPDATE `areatrigger_teleport` SET `name`='El Bastión Violeta (Salida)' WHERE `id`='5211';
UPDATE `areatrigger_teleport` SET `name`='La Matanza de Stratholme (Salida)' WHERE `id`='5148';
UPDATE `areatrigger_teleport` SET `name`='La Matanza de Stratholme (Entrada)' WHERE `id`='5150';
UPDATE `areatrigger_teleport` SET `name`='The Gate WoTLK' WHERE `id`='5047';
UPDATE `areatrigger_teleport` SET `name`='The Gate Classic' WHERE `id`='5046';
UPDATE `areatrigger_teleport` SET `name`='Dalaran teletransportador bueno' WHERE `id`='5273';
UPDATE `areatrigger_teleport` SET `name`='Ulduar, Cámaras de Relámpagos (Entrada)' WHERE `id`='5093';
UPDATE `areatrigger_teleport` SET `name`='Ulduar, Cámaras de Piedra (Salida)' WHERE `id`='5012';
UPDATE `areatrigger_teleport` SET `name`='Ulduar, Cámaras de Piedra (Entrada)' WHERE `id`='5010';
UPDATE `areatrigger_teleport` SET `name`='Drak\'Tharon Fortaleza (Salida)' WHERE `id`='5000';
UPDATE `areatrigger_teleport` SET `name`='Drak\'Tharon Fortaleza (Entrada)' WHERE `id`='4998';
UPDATE `areatrigger_teleport` SET `name`='Utgarde Fortaleza (Salida)' WHERE `id`='4743';
UPDATE `areatrigger_teleport` SET `name`='Utgarde Fortaleza (Entrada)' WHERE `id`='4745';
UPDATE `areatrigger_teleport` SET `name`='Azjol-Nerub (Salida)' WHERE `id`='5115';
UPDATE `areatrigger_teleport` SET `name`='Cámara de Archavon (Salida)' WHERE `id`='5262';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Entrada1)' WHERE `id`='5191';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Entrada2)' WHERE `id`='5192';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Entrada3)' WHERE `id`='5193';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Entrada4)' WHERE `id`='5194';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Salida1)' WHERE `id`='5196';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Salida2)' WHERE `id`='5197';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Salida3)' WHERE `id`='5198';
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Salida4)' WHERE `id`='5199';
UPDATE `areatrigger_teleport` SET `name`='Azjol-Nerub (Entrada)' WHERE `id`='5117';
UPDATE `areatrigger_teleport` SET `name`='Ahn\'Kahet (Entrada)' WHERE `id`='5215';
UPDATE `areatrigger_teleport` SET `name`='Cámara de los Aspectos, Sagrario Obsidiana (Entrada)' WHERE `id`='5243';
UPDATE `areatrigger_teleport` SET `name`='El Oculus (Entrada)' WHERE `id`='5246';
UPDATE `areatrigger_teleport` SET `name`='El Ojo de la Eternidad (Entrada)' WHERE `id`='5290';
UPDATE `areatrigger_teleport` SET `name`='Azjol-Nerub (Salida back)' WHERE `id`='5113';
UPDATE `areatrigger_teleport` SET `name`='Ulduar, Cámaras de Relámpagos (Salida)' WHERE `id`='5091';
UPDATE `areatrigger_teleport` SET `name`='Gundrak (Salida sur)' WHERE `id`='5231';
UPDATE `areatrigger_teleport` SET `name`='Gundrak - salida 01' WHERE `id`='5233';
UPDATE `areatrigger_teleport` SET `name`='Gundrak - salida 03' WHERE `id`='5276';
UPDATE `areatrigger_teleport` SET `name`='Gundrak (Salida norte)' WHERE `id`='5277';
UPDATE `areatrigger_teleport` SET `name`='Ahn\'Kahet (Salida)' WHERE `id`='5213';
UPDATE `areatrigger_teleport` SET `name`='Gundrak (Entrada norte)' WHERE `id`='5206';
UPDATE `areatrigger_teleport` SET `name`='Gundrak (Entrada sur)' WHERE `id`='5205';
UPDATE `areatrigger_teleport` SET `name`='Cámara de los Aspectos, Sagrario Obsidiana (Salida)' WHERE `id`='5241';
UPDATE `areatrigger_teleport` SET `name`='Karazhan, Servicio (Salida)' WHERE `id`='4520';
UPDATE `areatrigger_teleport` SET `name`='Ahn\'Kahet (salida)' WHERE `id`='5235';
UPDATE `areatrigger_teleport` SET `name`='Matanza de Stratholme (Salida)' WHERE `id`='5181';
UPDATE `areatrigger_teleport` SET `name`='Ulduar Raid Entrada' WHERE `id`='5379';
UPDATE `areatrigger_teleport` SET `name`='Ulduar (Tranvía)' WHERE `id`='5432';
UPDATE `areatrigger_teleport` SET `name`='Ulduar (Tranvía)' WHERE `id`='5402';
UPDATE `areatrigger_teleport` SET `name`='Ulduar (Planetarium)' WHERE `id`='5433';
UPDATE `areatrigger_teleport` SET `name`='Ulduar (Galería)' WHERE `id`='5390';
UPDATE `areatrigger_teleport` SET `name`='Ulduar Raid Salida' WHERE `id`='5381';
UPDATE `areatrigger_teleport` SET `name`='Cámara de Archavon (Entrada)' WHERE `id`='5258';
UPDATE `areatrigger_teleport` SET `name`='Prueba del Cruzado (Salida)' WHERE `id`='5508';
UPDATE `areatrigger_teleport` SET `name`='Prueba del Cruzado (Entrada)' WHERE `id`='5503';
UPDATE `areatrigger_teleport` SET `name`='Prueba del Campeón (Entrada)' WHERE `id`='5505';
UPDATE `areatrigger_teleport` SET `name`='Prueba del Campeón (Salida)' WHERE `id`='5510';
UPDATE `areatrigger_teleport` SET `name`='q12019: piso 1 antes de hacer la misión' WHERE `id`='5332';
UPDATE `areatrigger_teleport` SET `name`='q12019: piso 2 antes de hacer la misión' WHERE `id`='5340';
UPDATE `areatrigger_teleport` SET `name`='q12019: piso 2 despues de hacer la misión' WHERE `id`='5338';
UPDATE `areatrigger_teleport` SET `name`='q12019: piso 1 despues de hacer la misión' WHERE `id`='5334';
UPDATE `areatrigger_teleport` SET `name`='Zul\'drak - Voltarus, subiendo' WHERE `id`='5051';
UPDATE `areatrigger_teleport` SET `name`='Zul\'drak - Voltarus, bajando' WHERE `id`='5079';
UPDATE `areatrigger_teleport` SET `name`='q12710: planta 1' WHERE `id`='5080';
UPDATE `areatrigger_teleport` SET `name`='q12710: Planta baja' WHERE `id`='5061';
UPDATE `areatrigger_teleport` SET `name`='Cámaras de Reflexión (Entrada)' WHERE `id`='5636';
UPDATE `areatrigger_teleport` SET `name`='Cámaras de Reflexión (Salida)' WHERE `id`='5646';
UPDATE `areatrigger_teleport` SET `name`='Forja de Almas (Salida)' WHERE `id`='5688';
UPDATE `areatrigger_teleport` SET `name`='Forja de Almas (Salida)' WHERE `id`='5642';
UPDATE `areatrigger_teleport` SET `name`='Forja de Almas (Entrada)' WHERE `id`='5635';
UPDATE `areatrigger_teleport` SET `name`='Ciudadela de la Corona de Hielo (Salida)' WHERE `id`='5668';
UPDATE `areatrigger_teleport` SET `name`='Ciudadela de la Corona de Hielo (Entrada)' WHERE `id`='5670';
UPDATE `areatrigger_teleport` SET `name`='Foso de Saron (Salida)' WHERE `id`='5643';
UPDATE `areatrigger_teleport` SET `name`='Foso de Saron (Salida)' WHERE `id`='5683';
UPDATE `areatrigger_teleport` SET `name`='Foso de Saron (Entrada)' WHERE `id`='5637';
UPDATE `areatrigger_teleport` SET `name`='Ciudadela Corona de Hielo, La Aguja (Entrada)' WHERE `id`='5698';
UPDATE `areatrigger_teleport` SET `name`='Ciudadela Corona de Hielo, La Aguja (Salida)' WHERE `id`='5700';
UPDATE `areatrigger_teleport` SET `name`='q11898: piso 1 despues de hacer la misión' WHERE `id`='5339';
UPDATE `areatrigger_teleport` SET `name`='q11898: piso 2 antes de hacer la misión' WHERE `id`='5341';
UPDATE `areatrigger_teleport` SET `name`='Ciudadela Corona de Hielo, El Trono Helado (Entrada)' WHERE `id`='5718';
UPDATE `areatrigger_teleport` SET `name`='El Santuario Rubí (Entrada)' WHERE `id`='5869';
UPDATE `areatrigger_teleport` SET `name`='El Santuario Rubí (Salida)' WHERE `id`='5872';
