-- ======================= --
--   CREATURE_AI_TEXTS     --
-- ======================= --

ALTER TABLE `locales_quest` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
INSERT IGNORE INTO `locales_quest` (`entry`) SELECT `entry` FROM `quest_template`;

UPDATE `creature_ai_texts` SET `content_loc6`='Parece que esos idiotas de la Abadía nos han enviado carne fresca.' WHERE `entry`='-1' ;
UPDATE `creature_ai_texts` SET `content_loc6`='La Hermandad no tolerará tus actos.' WHERE `entry`='-2' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Ah, una oportunidad para usar esta hoja recién afilada.' WHERE `entry`='-3' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Siente el poder de la Hermandad!' WHERE `entry`='-4' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Más huesos para roer...' WHERE `entry`='-5' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Grrrr... ¡carne fresca!' WHERE `entry`='-6' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Tú no llevarte vela!' WHERE `entry`='-7' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Yujuuuuuu! ¡Yo correr!.' WHERE `entry`='-8' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Qué significa esta impertinencia? ¡Moriréis!' WHERE `entry`='-9' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Gritad mientras ardeis!' WHERE `entry`='-10' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Os incineraré!' WHERE `entry`='-11' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Me regocijo con tu dolor!' WHERE `entry`='-12' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Quieres un premio, eh? ¿Qué tal la muerte?' WHERE `entry`='-13' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Tu vida será mia!' WHERE `entry`='-14' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Odio recordarte que te avisé...' WHERE `entry`='-15' ;
UPDATE `creature_ai_texts` SET `content_loc6`='No iréis... muy lejos.' WHERE `entry`='-16' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Qué haceis? ¡Estos especímenes son muy delicados!' WHERE `entry`='-17' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡La naturaleza se somete a mi voluntad!' WHERE `entry`='-18' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Endorel aluminor!' WHERE `entry`='-19' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Ha concluido tu ciclo vital!' WHERE `entry`='-20' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Hay que conservar... los especímenes...' WHERE `entry`='-21' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Van Cleef pagará mucho por vuestras cabezas!' WHERE `entry`='-22' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡En guardia!' WHERE `entry`='-23' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Defendeos, aunque no os servirá de mucho...' WHERE `entry`='-24' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Lo sabía, sabía que... era la unica salida.' WHERE `entry`='-25' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Si, muy satisfactorio.' WHERE `entry`='-26' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Al fin, un objetivo para mis frustraciones!' WHERE `entry`='-27' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Habéis venido para matar a Dalliah? ¿Puedo mirar?' WHERE `entry`='-28' ;
UPDATE `creature_ai_texts` SET `content_loc6`='La oscuridad... lo consume todo.' WHERE `entry`='-29' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Las sombras... os engullirán.' WHERE `entry`='-30' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Este... ya está vacío.' WHERE `entry`='-31' ;
UPDATE `creature_ai_texts` SET `content_loc6`='No... más... vida.' WHERE `entry`='-32' ;
UPDATE `creature_ai_texts` SET `content_loc6`='El vacío... se avecina.' WHERE `entry`='-33' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Dar un paso adelante! Os daré la bienvenida que os merecéis.' WHERE `entry`='-34' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Oh, deja de lloriquear.' WHERE `entry`='-35' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Aún no... he empezado...' WHERE `entry`='-36' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Ya no os enfrentáis a un subordinado.' WHERE `entry`='-37' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Band\'or shorel\'aran!' WHERE `entry`='-38' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Guardias! ¡Reducir a los invasores!' WHERE `entry`='-39' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Es éste el final?' WHERE `entry`='-40' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Ha llegado la hora de que te unas a nosotros, $C.' WHERE `entry`='-42' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡No!' WHERE `entry`='-43' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡Estoy acabado!' WHERE `entry`='-44' ;
UPDATE `creature_ai_texts` SET `content_loc6`='El maestro... se enfadará...' WHERE `entry`='-45' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s se enfureció!' WHERE `entry`='-46' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡%s intenta huir despavorido!' WHERE `entry`='-47' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Espera... ¡No! ¡No!' WHERE `entry`='-49' ;
UPDATE `creature_ai_texts` SET `content_loc6`='No es... justo...' WHERE `entry`='-50' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Tómate esto, te ayudará.' WHERE `entry`='-344' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Te pondrás bien.' WHERE `entry`='-345' ;
UPDATE `creature_ai_texts` SET `content_loc6`='De repente, estaban en todas partes.' WHERE `entry`='-416' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Si el Capitán se entera, será mi fin.' WHERE `entry`='-414' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Alguien tuvo que ayudarles.' WHERE `entry`='-415' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Anaia?... ¿Me engañan mis ojos? ¿Eres tú de verdad?' WHERE `entry`='-661' ;
UPDATE `creature_ai_texts` SET `content_loc6`='El destino ha sido muy cruel al permitirnos volver a estar juntos solo tras miles de años de separación...' WHERE `entry`='-662' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Me odias, amor mío? Por haber tenido que destruir tu forma viviente y por liberar tu espíritu de tan triste cautiverio...' WHERE `entry`='-663' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¡No! Anaia... ¡Anaia! ¡No me abandones! Por favor...' WHERE `entry`='-664' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Cómo, amor mío? ¿Cómo encontraré fuerzas para enfrentarme a las edades del mundo sin ti a mi lado...' WHERE `entry`='-665' ;
UPDATE `creature_ai_texts` SET `content_loc6`='El ha sido cruel con nosotros, amor mío, pero ten por seguro que ahora sí permaneceremos unidos.' WHERE `entry`='-666' ;
UPDATE `creature_ai_texts` SET `content_loc6`='No permitas que esto atormente tu corazón, amor mío. Me has liberado de la esclavitud y por ello te amo más aún.' WHERE `entry`='-667' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Desafortunadamente, esto también debe interrumpirse... Los lazos que me atan a este mundo se debilitan y me arrastran...' WHERE `entry`='-668' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Adiós, Cerellean, hasta que volvamos a reunirnos...' WHERE `entry`='-669' ;
UPDATE `creature_ai_texts` SET `content_loc6`='La suave voz de Anaia se desvanece entre la niebla, \"No olvides que siempre te amaré...\"' WHERE `entry`='-670' ;
UPDATE `creature_ai_texts` SET `content_loc6`='¿Eso son jacintos de invierno? ¿Para mí?' WHERE `entry`='-7131' ;
UPDATE `creature_ai_texts` SET `content_loc6`='Ha pasado mucho tiempo desde que un viajero trajo flores aquí.' WHERE `entry`='-7012' ;
UPDATE `creature_ai_texts` SET `content_loc6`='El lago ha estado muy solitario estos últimos años. Los viajeros dejaron de venir y el mal se apoderó de estas aguas.' WHERE `entry`='-7011' ;
