-- ================== --
--     GAME_EVENT     --
-- ================== --

ALTER TABLE `game_event` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
UPDATE `game_event` set `description`='Festival de Fuego del Solsticio de Verano' where `eventEntry`='1';
UPDATE `game_event` set `description`='Festival de Invierno' where `eventEntry`='2';
UPDATE `game_event` set `description`='Feria de la Luna Negra (Bosque de Terokkar)' where `eventEntry`='3';
UPDATE `game_event` set `description`='Feria de la Luna Negra (Bosque de Elwynn)' where `eventEntry`='4';
UPDATE `game_event` set `description`='Feria de la Luna Negra (Mulgore)' where `eventEntry`='5';
UPDATE `game_event` set `description`='Víspera de Año Nuevo' where `eventEntry`='6';
UPDATE `game_event` set `description`='Festival Lunar' where `eventEntry`='7';
UPDATE `game_event` set `description`='Amor en el aire' where `eventEntry`='8';
UPDATE `game_event` set `description`='Jardín Noble' where `eventEntry`='9';
UPDATE `game_event` set `description`='Semana de los Niños' where `eventEntry`='10';
UPDATE `game_event` set `description`='Festival de la Cosecha' where `eventEntry`='11';
UPDATE `game_event` set `description`='Halloween' where `eventEntry`='12';
UPDATE `game_event` set `description`='Invasión de Elementales' where `eventEntry`='13';
UPDATE `game_event` set `description`='Va a comenzar la Fiesta de la Pesca en Tuercespina' where `eventEntry`='14';
UPDATE `game_event` set `description`='Fiesta de la Pesca en Tuercespina' where `eventEntry`='15';
UPDATE `game_event` set `description`='Captura del Botín en Arena Gurubashi' where `eventEntry`='16';
UPDATE `game_event` set `description`='Invasión de la Plaga' where `eventEntry`='17';
UPDATE `game_event` set `description`='Llamamiento a las armas: Valle de Alterac' where `eventEntry`='18';
UPDATE `game_event` set `description`='Llamamiento a las armas: Garganta Grito de Guerra' where `eventEntry`='19';
UPDATE `game_event` set `description`='Llamamiento a las armas: Cuenca de Arathi' where `eventEntry`='20';
UPDATE `game_event` set `description`='Llamamiento a las armas: Ojo de la Tormenta' where `eventEntry`='21';
UPDATE `game_event` set `description`='Refuerzos para Anh Qiraj' where `eventEntry`='22';
UPDATE `game_event` set `description`='Feria de la Luna Negra en construcción (Bosque de Elwynn)' where `eventEntry`='23';
UPDATE `game_event` set `description`='Fiesta de la cerveza' where `eventEntry`='24';
UPDATE `game_event` set `description`='Anochece' where `eventEntry`='25';
UPDATE `game_event` set `description`='Locura de Espadas, Gri\'lek' where `eventEntry`='27';
UPDATE `game_event` set `description`='Locura de Espadas, Hazza\'rah' where `eventEntry`='28';
UPDATE `game_event` set `description`='Locura de Espadas, Renataki' where `eventEntry`='29';
UPDATE `game_event` set `description`='Locura de Espadas, Wushoolay' where `eventEntry`='30';
UPDATE `game_event` set `description`='Torneo de Arenas' where `eventEntry`='31';
UPDATE `game_event` set `description`='Concierto de los L70ETC en Bosque Terokkar' where `eventEntry`='32';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 1 - Reclamando el Sagrario' where `eventEntry`='33';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 1 - Reclamando el Sagrario COMPLETA' where `eventEntry`='34';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 2 - Arsenal de Tramo del Sol' where `eventEntry`='35';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 2 - Arsenal de Tramo del Sol COMPLETA' where `eventEntry`='36';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 2b - Activando el Portal de La Fuente del Sol' where `eventEntry`='37';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 2b - Activando el Portal de La Fuente del Sol COMPLETA' where `eventEntry`='38';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 3 - Puerto de Tramo del Sol' where `eventEntry`='39';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 3 - Puerto de Tramo del Sol COMPLETA' where `eventEntry`='40';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 3b - Reconstruyendo el Yunque y la Forja' where `eventEntry`='41';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 3b - Reconstruyendo el Yunque y la Forja COMPLETA' where `eventEntry`='42';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 4A - Creando el Laboratorio de Alquímia' where `eventEntry`='43';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 4A - Creando el Laboratorio de Alquímia COMPLETA' where `eventEntry`='44';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 4B - Construyendo el Monumento a los Caídos' where `eventEntry`='45';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 4B - Construyendo el Monumento a los Caídos COMPLETA' where `eventEntry`='46';
UPDATE `game_event` set `description`='Ofensiva del Sol Devastado: Fase 4 - COMPLETA' where `eventEntry`='47';
UPDATE `game_event` set `description`='Defensa de la Alianza en Conquista del Invierno' where `eventEntry`='48';
UPDATE `game_event` set `description`='Defensa de la Horda en Conquista del Invierno' where `eventEntry`='49';
UPDATE `game_event` SET `description`='Día de los Piratas' WHERE `eventEntry`='50';
UPDATE `game_event` SET `description`='Festividad de los Muertos' WHERE `eventEntry`='51';
UPDATE `game_event` SET `description`='Festival de Invierno: Regalos' WHERE `eventEntry`='52';
UPDATE `game_event` SET `description`='Llamamiento a las armas: Playa de los Ancestros' WHERE `eventEntry`='53';
UPDATE `game_event` SET `description`='Llamamiento a las armas: Isla de la Conquista' WHERE `eventEntry`='54';
UPDATE `game_event` SET `description`='Temporada 3 de arenas' WHERE `eventEntry`='55';
UPDATE `game_event` SET `description`='Temporada 4 de arenas' WHERE `eventEntry`='56';
UPDATE `game_event` SET `description`='Temporada 5 de arenas' WHERE `eventEntry`='57';
UPDATE `game_event` SET `description`='Temporada 6 de arenas' WHERE `eventEntry`='58';
UPDATE `game_event` SET `description`='Temporada 7 de arenas' WHERE `eventEntry`='59';
UPDATE `game_event` SET `description`='Temporada 8 de arenas' WHERE `eventEntry`='60';
UPDATE `game_event` SET `description`='Caída de Zalazane' WHERE `eventEntry`='61';
UPDATE `game_event` SET `description`='Gran espectáculo de pesca' WHERE `eventEntry`='62';
UPDATE `game_event` SET `description`='Competición de pesca Kalu\'ak' WHERE `eventEntry`='63';
UPDATE `game_event` SET `description`='Competición de pesca Kalu\'ak en los bancos de pesca' WHERE `eventEntry`='64';